### ISSUE TITLE
missing definition of "collection" on Item type

### ISSUE THREAD

**Issue by keul** [blacha/stac-ts#50]
The current definition of the STAC Item type does not include `collection` which, by [STAC definition](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#item-fields), should be a string.

The [current fallback implementation](https://github.com/blacha/stac-ts/blob/21f2b1bfd4d03b26367486eec29c3fd553914452/src/types/item.d.ts#L33) rely only on `unknown` type, which gives some headhakes.

How to fix: explicitly add `collection` property

**Comment by blacha** [comment]
Looks like the `collection` property is defined in a complex way which was not supported by json schema to typescript

https://github.com/radiantearth/stac-spec/blob/v1.0.0/item-spec/json-schema/item.json#L156

So I have just manually added the field in, I think it should only exist if the `links` contain a `rel: collection` but I'm not sure there is a way to determine that in typescript easily.
