### ISSUE TITLE
Problem with linting

### ISSUE THREAD

**Issue by marksmall** [blacha/stac-ts#61]
I tried to use these type definitions on a project I'm working on but it is causing ESLint to break and therefore the building of the app. The cause is the `main` line in the `package.json` file. It states the main file of the library is `index.js` but no such file exists. If there is no main entrypoint into the library, then it is best not to set a `main` at all.

I did a quick test to remove this line from the installed version of the library and everything worked well afterwards, so I think if it were removed permanently. I can create a PR if you like, just not sure if this library is maintained or if it would be better for us to fork the whole repo?

**Comment by blacha** [comment]
Thanks for reporting this @marksmall! I have fixed it with https://github.com/blacha/stac-ts/pull/62

This library is still in use across a number of project, I just haven't had much need to add any new features to it, I have been wondering about how to make a v1.1.0 variant to align with the new STAC v1.1.0 release https://github.com/radiantearth/stac-spec/commit/0622368dd54a4152f70292ab5671cb1337bc6ebb
